### ISSUE TITLE
In development mode, when the '. less' is modified, the cache is not updated

### ISSUE THREAD

**Issue by noisnaaria** [neilime/zf2-assets-bundle#28]
'asset_bundle' => array(
        'production' => false,
        'assets' => array(
            'less' => array('less'),
            'js' => array(
                'js/jquery.min.js',
                'js/bootstrap.min.js'
            ),
            'media' => array(
                'img',
                'fonts'
            ),
        )
    ),

**Comment by neilime** [comment]
Fixed in Version 3.5.3
