### ISSUE TITLE
issue cached files

### ISSUE THREAD

**Issue by apoca** [neilime/zf2-assets-bundle#30]
I have this error:

Fatal error: Uncaught exception 'LogicException' with message '"/usr/local/zend/var/apps/http/esolidar.bewarket.setima.local/80/0.1/public/images/about/logo.png" has not been cached as file "/usr/local/zend/var/apps/http/esolidar.bewarket.setima.local/80/0.1/public/cache/fb4a13125a55e864c0b8368d1f8b386d/logo.png"' in /usr/local/zend/var/apps/http/esolidar.bewarket.setima.local/80/0.1/vendor/neilime/zf2-assets-bundle/src/AssetsBundle/Service/Service.php:1045 Stack trace: #0 [internal function]: AssetsBundle\Service\Service->rewriteUrl(Array, '/usr/local/zend...') #1 /usr/local/zend/var/apps/http/esolidar.bewarket.setima.local/80/0.1/vendor/neilime/zf2-assets-bundle/src/AssetsBundle/Service/Service.php(673): call_user_func(Array, Array, '/usr/local/zend...') #2 [internal function]: AssetsBundle\Service\Service->AssetsBundle\Service{closure}(Array) #3 /usr/local/zend/var/apps/http/esolidar.bewarket.setima.local/80/0.1/vendor/neilime/zf2-assets-bundle/src/AssetsBundle/Service/Service.php(675): preg_replace_callback('/url(([ in /usr/local/zend/var/apps/http/esolidar.bewarket.setima.local/80/0.1/vendor/neilime/zf2-assets-bundle/src/AssetsBundle/Service/Service.php on line 1045

**Comment by neilime** [comment]
Do you have fixed your error ?
