### ISSUE TITLE
Subfolders images

### ISSUE THREAD

**Issue by jjamaral** [neilime/zf2-assets-bundle#40]
Hi @neilime,

First of all, congratulations for this bundle, its pretty cool!

Im having a small issue with subfolders search. I have this flag setted to true:
'recursiveSearch' => true

My media property:
'media' => array('img','fonts','plugins')

But, only plugins folder and "first subfolder" is cached.
Example: /plugins/font-awesome/images/ isnt cached.

Do you know why? How can I solve this?

Thanks in advance!

**Comment by neilime** [comment]
Old issue, was fixed in an old previous version
