### ISSUE TITLE
Vendor image cached but not accessible

### ISSUE THREAD

**Issue by dada87** [neilime/zf2-assets-bundle#42]
Hi,

First of great job with this module.

I have a question : I created a external module that I load through composer. In this module I have a 'vendor/.../my-module/resources/img/loader.gif' that is well cached by your module.
My problem is that even thought I see the file in the cache directory I can't access it in my rendered HTML except when I write the full path to the cached file.

Is there a way to get the cache file URL from your module so that I can access my vendor img dynamically ?

Thanks
David

**Comment by neilime** [comment]
If you use this image in your css / less, the path will be rewrited. There's no helpers that can render cached path to be be used directly into views.
Actually, it may be a usefull feature.

**Comment by dada87** [comment]
Indeed it would :)
Thanks for the reply.
