### ISSUE TITLE
Deprecated: ServiceLocatorAwareInterface

### ISSUE THREAD

**Issue by andrconstruction** [neilime/zf2-assets-bundle#43]
Hi  neilime! Thanks for your products.
Please help me if you can.

Afer upgrade ZF2 I had next error :
Deprecated: ServiceLocatorAwareInterface is deprecated and will be removed in version 3.0, along with the ServiceLocatorAwareInitializer. Please update your class AssetsBundle\View\Strategy\JsCustomStrategy to remove the implementation, and start injecting your dependencies via factory instead. in /var/www/clients/client1/web1/web/z/vendor/zendframework/zend-mvc/src/Service/ServiceManagerConfig.php on line 151
But as I see that in config JsCustomStrategy created through Factory already. what is wrong?
How can I avoid this error by other methods excluding  a E_NOTICE off?

**Comment by jens-kompter** [comment]
This issue is fixed now.

**Comment by andrconstruction** [comment]
Yep, I saw, thank you very much
