### ISSUE TITLE
Disable media 'optimazation'

### ISSUE THREAD

**Issue by chielsen** [neilime/zf2-assets-bundle#46]
I don't want to ruin my images. By default it will run all images through the filters, but thusfar i have not found a way to disable running the default filters as i cannot unset the key and setting the filter null will just run the previously used filer (bug?).
Am i missing something or could this be added?

**Comment by neilime** [comment]
Hi,

In your assets_bundle config, you can disabled filters for image : 
```php
 'filters' => array(
        'png' => null,
        'jpg' => null, 'jpeg' => null,
        'gif' => null,
    ),
```

You can try this config.

**Comment by neilime** [comment]
Does it work for you ?

**Comment by chielsen** [comment]
`		'filters' => [
			'jpg' => new \Zend\Stdlib\ArrayUtils\MergeRemoveKey(), 'jpeg' => new \Zend\Stdlib\ArrayUtils\MergeRemoveKey(),
		],
`

This works for me.

**Comment by neilime** [comment]
Thank you I add this trick to FAQ : https://github.com/neilime/zf2-assets-bundle/wiki/FAQ#how-to-disable-media-optimization
