### ISSUE TITLE
Going to unknown Controller throws uncaught ServiceNotFoundException

### ISSUE THREAD

**Issue by chielsen** [neilime/zf2-assets-bundle#47]
In AssetsBundle\Service\Service on line 96 you are getting the Controller class, without checking if it exists. So instead of showing a 404 page, I'm getting an uncaught Exception.

Maybe check if an error param is given or check if the class can be loaded

**Comment by neilime** [comment]
PLease

**Comment by chielsen** [comment]
Cool, thanks for the quick response :)

**Comment by chielsen** [comment]
A but it's not working, fix should be:

if ($oControllerLoader->has($sControllerName) && ($oController = $oControllerLoader->get($sControllerName))) {

**Comment by neilime** [comment]
Sure, you're right. Sorry for this error. 
Fixed.
