### ISSUE TITLE
How can I prevent merge JS file

### ISSUE THREAD

**Issue by justinphan1992** [neilime/zf2-assets-bundle#50]
Hi neilime.

Thank you to create nice tool to mannage the asset files. I have problem when turn on production mode the javascript file occurred error. Is there any way to turn off merge files just in javascript

**Comment by neilime** [comment]
There's no way to turn off mergin files for javascript at the moment. Maybe you can try to use an another javascript filter :
```php
array(
    'assets_bundle' => array(
        'filters' => array(
            \AssetsBundle\AssetFile\AssetFile::ASSET_JS => 'JsMinAssetFileFilter',
        ),
    ),
);
```
Tell me if it works for you

**Comment by justinphan1992** [comment]
Thank for your response

I tried but didnt work.

**Comment by neilime** [comment]
Or you can try to disable the JavaScript filter : 

```php
array(
    'assets_bundle' => array(
        'filters' => array(
            \AssetsBundle\AssetFile\AssetFile::ASSET_JS => new \Zend\Stdlib\ArrayUtils\MergeRemoveKey(),
        ),
    ),
);
```

**Comment by neilime** [comment]
Have you tried the previous solution ?
