### ISSUE TITLE
JsShink is corrupting js files

### ISSUE THREAD

**Issue by chielsen** [neilime/zf2-assets-bundle#51]
Sinced you changed to JsShrink some of my js files are corrupted. It removes too many spaces. Could you change it back?

**Comment by neilime** [comment]
You can define which js filter you want to use in configuration : 
```php
array(
    'assets_bundle' => array(
        'filters' => array(
            \AssetsBundle\AssetFile\AssetFile::ASSET_JS => 'JsMinAssetFileFilter',
        ),
    ),
);

**Comment by neilime** [comment]
Have you tried the previous solutions ?
