### ISSUE TITLE
Bootstrap does not work in windows environment

### ISSUE THREAD

**Issue by wambaloo** [neilime/zf2-assets-bundle#53]
I try to use this module with Bootstrap 3. I added in my composer the require to Bootstrap library and I configured my application to get the "less" bootstrap file. But in vain, when I want to display a page, I've got the following error : 
`Fatal error: Uncaught exception 'RuntimeException' with message 'Error occured while creating directory "C:\wamp64\www\cvs_pdl\pdl\bo\public\cache\C:\wamp64\www\cvs_pdl\pdl\vendor\twbs\bootstrap\fonts"' in C:\wamp64\www\cvs_pdl\pdl\vendor\neilime\zf2-assets-bundle\src\AssetsBundle\AssetFile\AssetFilesCacheManager.php on line 147`

I notice that the path generated to cache files, when using the @zfPath variable, is an absolute path, which produce this error. Maybe I missed something in configuration ?

Thanks in advance !

**Comment by neilime** [comment]
Please, can you try the very last version if it works for you now.

**Comment by wambaloo** [comment]
Thanks for update !! it works like a charm now !
I still have a problem with bootstrap fonts. I have 404 errors when try to load glyphicon files. It tries to load "file:///C:/path_to_project_root/vendor/twbs/bootstrap/less/fonts/glyphicons-halflings-regular.woff2" but I configured the bundle like that : 
`'media' => array(
                '@zfRootPath/vendor/twbs/bootstrap/fonts'
            ),
            'less' => array(
                '@zfRootPath/vendor/twbs/bootstrap/less/bootstrap.less'
            )`

So I don't know what I missed...

**Comment by wambaloo** [comment]
I have to precise that my application is structured like this :
`app/
  bo/
    config/
      application.config.php
  vendor/
    twbs/...`

So maybe it's due to my architecture... I have tried to change, in variables.less file, value "@icon-font-path:          "../fonts/";" to "@icon-font-path:          "../../fonts/";". Url generated is good but still have a 404 error. If I type the file url in navigator (file url retrieve from chrome console, the same loaded in my homepage), its download the woff2 file, so url is right. I really don't understand what happened...

**Comment by wambaloo** [comment]
Another comment : if I include only CSS files, module generate an empty  dev_xxxxxxx.css file, and in network console view of chrome, it generate a 404 response.

**Comment by neilime** [comment]
An issue is created for the last comment : #56
