### ISSUE TITLE
Support for relative URL?

### ISSUE THREAD

**Issue by ubiquitous-tom** [neilime/zf2-assets-bundle#61]
Is there a way to just use 

```php
...
'js' => array(
    '//code.jquery.com/jquery-1.12.4.min.js',
    ...
),
...
```

instead of having to specify either http:// or https://

**Comment by neilime** [comment]
No there is no way at the moment

**Comment by ubiquitous-tom** [comment]
I see.

Awesome plugin and thank you for a quick reply!
