### ISSUE TITLE
Can php output in develop be cached?

### ISSUE THREAD

**Issue by chielsen** [neilime/zf2-assets-bundle#62]
I have a php script that should output JS code. This works fine in production and is cached. However on development the actual php coded is copied and not the output. Since I use` __DIR__ `, my script now cannot find the files it needs.

2 questions:

1.  is there a way i can use the `__DIR__` of the original file?
2. can the output of the script be cached? this would also work

**Comment by neilime** [comment]
You can use .php files as assets, there will be interpret, there cached if the file is not modified
