### ISSUE TITLE
Css is corrupted by minify

### ISSUE THREAD

**Issue by chielsen** [neilime/zf2-assets-bundle#63]
Some css files i'm loading are being corrupted by the older minifier that is being used. Since the css is loaded from another library it's not easy to change this.
I tried and with upgrading to mrclay/minify" version 3+ this is solved. 
I think there are no reasons not to upgrade, so please can you bump it?

**Comment by neilime** [comment]
A new version may be fit with your need ; https://github.com/neilime/zf2-assets-bundle/releases/tag/4.0.0

Tell me if it works fine, if not, we should improves unit tests againts your broken css files
